### ISSUE TITLE
add icon for Twitter link

### ISSUE THREAD

**Issue by cvan** [mozilla/moz-games#16]

**Comment by cvan** [comment]
we're linking to Twitter only now. we still could/should add this.

**Comment by deathping1994** [comment]
Hi Cvan , if I am correct you want to replace the text links with Twitter icon links , right ??
I want to take it up , if you are okay with it.
![screenshot from 2015-09-19 23 49 22](https://cloud.githubusercontent.com/assets/5563351/9977531/52452ace-5f29-11e5-8197-66b7d558c4b0.png)

**Comment by cvan** [comment]
thanks for the contiubtion, @deathping1994. we have since redesigned and removed the Twitter link. thanks though!
