### ISSUE TITLE
SSL Cert has expired

### ISSUE THREAD

**Issue by elebumm** [mozilla/moz-games#164]
Just went to check out games.mozilla.org but found out that the SSL cert has expired on the 19th.

**Comment by obitodarky** [comment]
For a better understanding

![Screenshot 2019-05-18 at 5 57 32 PM](https://user-images.githubusercontent.com/21317964/57969607-76ff2a00-7996-11e9-85f8-a0932b7377f1.png)

**Comment by cvan** [comment]
thanks for reporting. we're working on getting this back in service :+1:

**Comment by larsbergstrom** [comment]
I'm trying to figure out who can help with this internally now. Thanks for reporting!
